### ISSUE TITLE
1.0.7 requirements

### ISSUE THREAD

**Issue by benoitcdmnt** [qmachard/atomic-design-bundle#23]
Hello,

J'ai voulu tester d'installer le package (sur une app symfo PHP 8) en l'installant comme indiqué dans la doc, le package s'installe par défaut sur le dernier tag : 1.0.7 
* Les requirements ne permettent pas de l'installer sur PHP8 (je vois que sur ta master c'est ok)
* Une erreur remonte aussi car il n'y a pas le `require sensio/framework-extra-bundle` sur ce tag, et sur la route view tu as besoin du ParamConverter qui récupère le Component et qui du coup ne fonctionne pas si `sensio/framework-extra-bundle` n'est pas installé. Idem sur ta master c'est ok, on voit bien le require qui va bien.

Un nouveau tag de prévu avec les changements apportés dans master ?

**Comment by qmachard** [comment]
Hello,

Effectivement, la 1.0.7 est seulement un hotfix suite à des correctifs de sécurité. Je prévois une nouvelle release assez vite car ce sont effectivement des soucis que j'ai pu repéré suite à la mise en place des tests PHPSpec jeudi.

En attendant, si tu veux installer la version `dev-master` et me dire si cette version est pleinement fonctionnelle sur PHP 8, ce serait top !

Merci à toi,

**Comment by benoitcdmnt** [comment]
Yes c'est ce que j'avais fait du coup, pas eu de soucis particulier sur dev-master ça fonctionne bien sur PHP8 et le `sensio/framework-extra-bundle` s'est bien installé car require (je l'avais pas encore install de base). En tout cas si tu as besoin d'aide je serais intéressé pour contrib un peu dessus.

**Comment by qmachard** [comment]
Cool ! Je viens de déployer une nouvelle version sur master avec des tests fonctionnels. Je pense pouvoir créer la release 1.0.8 avec le support PHP 8, etc.

Tu peux contribuer avec grand plaisir, n'hésite pas à forker le repos et proposer tes améliorations, via PR. Je n'ai pas de Roadmap exhaustive pour le moment, mais il y a quelques issues qui pourrait être intéressantes à implémenter (je pense par exemple à celle ci #2).
