### ISSUE TITLE
Ajout du support de sensio/framework-extra-bundle v6

### ISSUE THREAD

**Issue by GErpeldinger** [qmachard/atomic-design-bundle#37]
Bonjour,

Sur une application récente en Symfony en version full (website-skeleton) la version de base de sensio/framework-extra-bundle est maintenant ^6.1, le bundle ne supporte actuellement que la version 5.

Pourrais-tu envisager d'ajouter le support de la dépendance dans ça version 6 pour éviter que composer nous renvoi un problème de requirement à l'installation du package?

**Comment by qmachard** [comment]
Bonjour,

Je viens de faire le test en installant un nouveau symfony (en version 5.3.* qui est la dernière version stable), même si le package `sensio/framework-extra-bundle` est compatible avec la version `^6.1`, il est rétro compatible avec la version `^5.3` de symfony.

```
# composer.json
{
  ...
  "require": {
    "sensio/framework-extra-bundle": "^6.1",
    ...
  },
  "require-dev": {
    "qmachard/atomic-design-bundle": "^1.0"
  }
}
```

Je pense que tu dois être en Symfony 6.0, j'ai tenté de rendre le package compatible, mais `symfony/twig-bundle` ne l'est pas encore en version stable.

**Comment by qmachard** [comment]
Même en mettant `symfony/twig-bundle` en version de dev, `symfony/webpack-encore-bundle` n'est pas du tout compatible symfony 6 pour le moment...

**Comment by GErpeldinger** [comment]
Hello,

Mon application est en Symfony 5.3 avec sensio/framework-extra-bundle en 6.1 (6.1.5 pour être exact) et comme tu peux le voir sur ce screen, j'ai des bien un problème de compatibilité :

<img width="1509" alt="Capture d’écran 2021-09-14 à 12 50 25" src="https://user-images.githubusercontent.com/60388866/133244707-44b7c63a-e37f-42fa-9b77-6b9b7922866b.png">

**Comment by GErpeldinger** [comment]
Je viens d'essayer de créer une nouvelle application symfony en 5.3 et y ajouter le bundle mais j'ai le même message d'erreur qui apparaît.

PS : les nouvelles applications en 5.3 ont de base sensio/framework-extra-bundle en version 6.1

**Comment by yann-eugone** [comment]
Hello, j'ai ouvert une PR pour cette issue.

Juste, SensioFrameworkExtraBundle a son propre cycle de versions, ça n'a aucun rapport avec la version majeure de Symfony.
Et donc, une application Symfony 5.x devrait déjà utiliser une version 6.x de ce bundle.

Il n'y a qu'à voir les requirements du bundle
https://packagist.org/packages/sensio/framework-extra-bundle
> **requires**
> symfony/config: ^4.4|^5.0|^6.0
> symfony/dependency-injection: ^4.4|^5.0|^6.0
> symfony/framework-bundle: ^4.4|^5.0|^6.0
> symfony/http-kernel: ^4.4|^5.0|^6.0

**Comment by qmachard** [comment]
Ça marche, merci :)

**Comment by qmachard** [comment]
Merged in Release 1.0.12.
